## DB연결

In [2]:
import cx_Oracle
import pandas as pd

# Oracle 데이터베이스 연결 설정
host = '192.168.30.206'
port = '1521'
sid = 'Sim_Party'
username = 'party'
password = 'party'

dsn_str = f'{username}/{password}@{host}:{port}/{sid}'
conn = cx_Oracle.connect(dsn_str)

# 쿼리 실행하여 데이터를 데이터프레임으로 불러오기
query = 'SELECT * FROM PLACEINFO_TEST'
df = pd.read_sql(query, conn)

# 불러온 데이터 확인
print(df.head())

# 연결 종료
conn.close()

DatabaseError: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

In [20]:
connection = cx_Oracle.connect("party/party@192.168.30.240:1521/Sim_Party")

DatabaseError: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

In [9]:
query = 'SELECT * FROM PLACEINFO_TEST'

In [11]:
df = pd.read_sql(query, connection)

C:\Users\tj-bu\AppData\Local\Temp\ipykernel_12964\1848774206.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)


In [12]:
df.head(5)

ID 카테고리   소분류      제목                        주소          전화번호          경도  \
0   1   관광  역사문화  강화 갑곶돈  인천 강화군 강화읍 해안동로1366번길 18  032-930-7000  126.515997   
1   2   관광  역사문화  강화 석수문   인천 강화군 강화읍 고비고개로19번길 12  032-930-4571  126.474572   
2   3   관광  역사문화     용흥궁  인천 강화군 강화읍 동문안길21번길 16-1          None  126.486012   
3   4   관광  역사문화  강화 전등사     인천 강화군 길상면 전등사로 37-41  032-937-0125  126.484406   
4   6   관광  역사문화  강화 초지진        인천 강화군 길상면 해안동로 58  032-930-7072  126.532262   

          위도                                         애완동물동반가능정보         주차시설  \
0  37.733579                                                 불가      있음 (무료)   
1  37.745366  가능 (단, 개목줄 착용, 배설물 처리를 위한 비닐봉지 등을 구비한 이용객에 한하여...      있음 (무료)   
2  37.747949  가능 (단, 개목줄 착용, 배설물 처리를 위한 비닐봉지 등을 구비한 이용객에 한하여...  있음 (30분 무료)   
3  37.632160                              불가(전등사 관람은 목줄과 함께 가능)      있음 (유료)   
4  37.632610                                                 불가      있음 (무료)   

   ...  판매품목  편의시설  대표메뉴 포장가능여부  입실시간  퇴실시간  부대시설 키워드리스트  \
0  ...  None  None  None   None  None  None  None   None   
1  ...  None  None  None   None  None  None  None   None   
2  ...  None  None  None   None  None  None  None   None   
3  ...  None  None  None   None  None  None  None   None   
4  ...  None  None  None   None  None  None  None   None   

                                              이미지주소1  \
0  https://dbscthumb-phinf.pstatic.net/2765_000_1...   
1  http://post.phinf.naver.net/MjAxOTExMjdfMjU1/M...   
2  https://dbscthumb-phinf.pstatic.net/5701_000_2...   
3  http://imgnews.naver.net/image/001/2020/09/24/...   
4  https://thumb2.gettyimageskorea.com/image_prev...   

                                              이미지주소2  
0  https://dbscthumb-phinf.pstatic.net/2765_000_1...  
1  https://cdn.visitkorea.or.kr/img/call?cmd=VIEW...  
2  https://minio.nculture.org/amsweb-opt/multimed...  
3  http://imgnews.naver.net/image/5157/2014/12/16...  
4  http://imgnews.naver.net/image/5364/2016/07/07...  

[5 rows x 26 columns]

In [18]:
df['키워드리스트']

0      None
1      None
2      None
3      None
4      None
       ... 
879    None
880    None
881    None
882    None
883    None
Name: 키워드리스트, Length: 884, dtype: object

In [16]:
df_new=df[['제목','키워드리스트']]

In [17]:
df_new.head(5)

제목 키워드리스트
0  강화 갑곶돈   None
1  강화 석수문   None
2     용흥궁   None
3  강화 전등사   None
4  강화 초지진   None

## DB연결 2

In [31]:
connection = cx_Oracle.connect("party/party@192.168.30.240:1521/xe")

query = """select * from PLACEINFO_TEST"""

df = pd.read_sql(query, con=connection)

C:\Users\tj-bu\AppData\Local\Temp\ipykernel_12964\3095652730.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)


In [29]:
df.head(5)

ID 카테고리   소분류      제목                        주소          전화번호          경도  \
0   1   관광  역사문화  강화 갑곶돈  인천 강화군 강화읍 해안동로1366번길 18  032-930-7000  126.515997   
1   2   관광  역사문화  강화 석수문   인천 강화군 강화읍 고비고개로19번길 12  032-930-4571  126.474572   
2   3   관광  역사문화     용흥궁  인천 강화군 강화읍 동문안길21번길 16-1          None  126.486012   
3   4   관광  역사문화  강화 전등사     인천 강화군 길상면 전등사로 37-41  032-937-0125  126.484406   
4   6   관광  역사문화  강화 초지진        인천 강화군 길상면 해안동로 58  032-930-7072  126.532262   

          위도                                         애완동물동반가능정보         주차시설  \
0  37.733579                                                 불가      있음 (무료)   
1  37.745366  가능 (단, 개목줄 착용, 배설물 처리를 위한 비닐봉지 등을 구비한 이용객에 한하여...      있음 (무료)   
2  37.747949  가능 (단, 개목줄 착용, 배설물 처리를 위한 비닐봉지 등을 구비한 이용객에 한하여...  있음 (30분 무료)   
3  37.632160                              불가(전등사 관람은 목줄과 함께 가능)      있음 (유료)   
4  37.632610                                                 불가      있음 (무료)   

   ...  판매품목  편의시설  대표메뉴 포장가능여부  입실시간  퇴실시간  부대시설 키워드리스트  \
0  ...  None  None  None   None  None  None  None   None   
1  ...  None  None  None   None  None  None  None   None   
2  ...  None  None  None   None  None  None  None   None   
3  ...  None  None  None   None  None  None  None   None   
4  ...  None  None  None   None  None  None  None   None   

                                              이미지주소1  \
0  https://dbscthumb-phinf.pstatic.net/2765_000_1...   
1  http://post.phinf.naver.net/MjAxOTExMjdfMjU1/M...   
2  https://dbscthumb-phinf.pstatic.net/5701_000_2...   
3  http://imgnews.naver.net/image/001/2020/09/24/...   
4  https://thumb2.gettyimageskorea.com/image_prev...   

                                              이미지주소2  
0  https://dbscthumb-phinf.pstatic.net/2765_000_1...  
1  https://cdn.visitkorea.or.kr/img/call?cmd=VIEW...  
2  https://minio.nculture.org/amsweb-opt/multimed...  
3  http://imgnews.naver.net/image/5157/2014/12/16...  
4  http://imgnews.naver.net/image/5364/2016/07/07...  

[5 rows x 26 columns]

In [32]:
df['키워드리스트'].head(5)

0       강화(50),맛집(10)
1       꿀잼(40),노잼(20)
2    다신안가요(60),최악(30)
3                None
4                None
Name: 키워드리스트, dtype: object

In [34]:
data=df[['카테고리','제목','주소','키워드리스트']]

In [35]:
data

카테고리         제목                        주소            키워드리스트
0     관광     강화 갑곶돈  인천 강화군 강화읍 해안동로1366번길 18     강화(50),맛집(10)
1     관광     강화 석수문   인천 강화군 강화읍 고비고개로19번길 12     꿀잼(40),노잼(20)
2     관광        용흥궁  인천 강화군 강화읍 동문안길21번길 16-1  다신안가요(60),최악(30)
3     관광     강화 전등사     인천 강화군 길상면 전등사로 37-41              None
4     관광     강화 초지진        인천 강화군 길상면 해안동로 58              None
..   ...        ...                       ...               ...
879   숙박  HOTEL 프라하            인천 미추홀구 토금북로 7              None
880   숙박      호텔소프라         인천 서구 서곶로301번길 21              None
881   숙박  오션사이드관광호텔             인천 중구 마시란로 40              None
882   숙박      오로라모텔          인천 미추홀구 인주대로 153              None
883   숙박      프라하모텔       인천 미추홀구 경인로435번길 10              None

[884 rows x 4 columns]

## 캐글 movie 데이터셋으로 연습해보기

In [46]:
movie_df=pd.read_csv('tmdb_5000_movies.csv')

In [47]:
movie_df.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [48]:
data=movie_df[['id','genres','vote_average','vote_count','popularity','title','keywords','overview']]

In [49]:
data.head(5)

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

## 전처리

* 평균평점이 불공정 처리 되어있음
* 데이터를 제공해준 imdb에서 제안한 weight rating으로 평점 다시 처리
* 그 공식 적용해서 socre컬럼 다시만듬

In [50]:
## 500위안에 들어올려면 vote_count가 상위 몇퍼인가 
m=data['vote_count'].quantile(0.9) ##quantile(0.9) => 데이터의 분포에서 90% 지점에 해당하는 값을 의미함. 하위 90%임 
#quantile은 함수의 데이터 분위스를 계상하는데 사용된다. 0.5는 중앙값, 0.25는 1사분위를 계산함
print(m) 

1838.4000000000015


In [51]:
data=data.loc[data['vote_count']>=m]

In [53]:
data.shape

(481, 8)

In [54]:
c=data['vote_average'].mean()

In [55]:
print(c)

6.962993762993763


In [56]:
def weight_rating(x, m=m,c=c):
    v=x['vote_count']
    r=x['vote_average']
    
    return(v/(v+m)*r)+(m/(v+m)*c)

In [57]:
data['score']=data.apply(weight_rating, axis=1)

C:\Users\tj-bu\AppData\Local\Temp\ipykernel_12964\1897495232.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['score']=data.apply(weight_rating, axis=1)


In [58]:
data.head()

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271  
2  A cryptic message from Bond’s past sends him o...  6.493333  
3  Following the death of District Attorney Harve...  7.492998  
4  John Carter is a war-weary, former military ca...  6.500396

## 콘텐츠기반 필터링을 위한 컬럼추출

* 사용자가 특정아이템을 선택한경우, 그 아이템과 비슿한 컨텐츠를 가진 다른아이템 추천해주는방식
* '비슷함'의 기준은 장르와 키워드로 분석할수 있음
* 장르와 키워드의 값은 list안의 dict이 포함된 구조임
* string으로 변환해주어야 하기떄문에 ast패키지안에있는 literal_eval로 변환시킨다.

In [60]:
data[['genres','keywords']].head()

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [61]:
import ast as ast

In [62]:
data['genres']=data['genres'].apply(ast.literal_eval)
data['keywords']=data['keywords'].apply(ast.literal_eval)

In [63]:
data[['genres','keywords']].head()

genres  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
3  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...   
4  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                            keywords  
0  [{'id': 1463, 'name': 'culture clash'}, {'id':...  
1  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...  
2  [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...  
3  [{'id': 849, 'name': 'dc comics'}, {'id': 853,...  
4  [{'id': 818, 'name': 'based on novel'}, {'id':...

* genres안의 값들을 dict형식으로 되어있어서 key를 가지고 뽑아올수있음
* 값을 string으로 변환해서 lambda식을써서 장르와 키워드값 변형시킴

In [64]:
data['genres']=data['genres'].apply(lambda x : [d['name'] for d in x]).apply(lambda x:" ".join(x))

In [65]:
data['keywords']=data['keywords'].apply(lambda x : [d['name'] for d in x]).apply(lambda x:" ".join(x))

In [66]:
data.head()

id                                    genres  vote_average  vote_count  \
0   19995  Action Adventure Fantasy Science Fiction           7.2       11800   
1     285                  Adventure Fantasy Action           6.9        4500   
2  206647                    Action Adventure Crime           6.3        4466   
3   49026               Action Crime Drama Thriller           7.6        9106   
4   49529          Action Adventure Science Fiction           6.1        2124   

   popularity                                     title  \
0  150.437577                                    Avatar   
1  139.082615  Pirates of the Caribbean: At World's End   
2  107.376788                                   Spectre   
3  112.312950                     The Dark Knight Rises   
4   43.926995                               John Carter   

                                            keywords  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   
2  spy based on novel secret agent sequel mi6 bri...   
3  dc comics crime fighter terrorist secret ident...   
4  based on novel mars medallion space travel pri...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271  
2  A cryptic message from Bond’s past sends him o...  6.493333  
3  Following the death of District Attorney Harve...  7.492998  
4  John Carter is a war-weary, former military ca...  6.500396

## 콘텐츠기반 필터링 추천

* 장르 벡터화 : 유사 장르를 추천해주는 경우. 장르들은 띄어쓰기가 구분된 한 문자열로 저장이 되어있음. 이 문자열을 숫자로 바꿔서 벡터화 시켜야한다.
* scikit learn에 있는 CountVectorizer를 사용한다


In [67]:
from sklearn.feature_extraction.text import CountVectorizer

In [70]:
count_vector = CountVectorizer(ngram_range=(1,3))

In [71]:
c_vector_genres = count_vector.fit_transform(data['genres'])

In [72]:
c_vector_genres.shape

(481, 364)

In [73]:
c_vector_genres

<481x364 sparse matrix of type '<class 'numpy.int64'>'
	with 3238 stored elements in Compressed Sparse Row format>

## 유사도값 추출(코사인유사도)

In [75]:
from sklearn.metrics.pairwise import cosine_similarity

In [77]:
similarity_genre = cosine_similarity(c_vector_genres, c_vector_genres).argsort()[:,::-1]

In [78]:
print(similarity_genre)

[[  0  13  42 ... 298 297 240]
 [ 11   1 200 ... 329 330 240]
 [  2 376 216 ... 314 304 240]
 ...
 [478 187  12 ... 326 327   0]
 [479 466 383 ... 220 224   0]
 [480 468 294 ... 246 248   0]]


In [79]:
similarity_genre.shape

(481, 481)

## 영화추천 함수 생성

* 영화제목 검색하면 유사한 장르의 영화를 추천해주게됨

In [84]:
def recommend_movie_list(df,movie_title,top=30):
    # 특정 영화정보 뽑아내기
    target_movie_index= df[df['title'] == movie_title].index.values
    
    # 타겟 영화와 비슷한 코사인유사도값
    sim_index = similarity_genre[target_movie_index,:top].reshape(-1)
    # 본인제외
    sim_index = sim_index[sim_index!=target_movie_index]
    
    # 추천결과 새로운 df생성, 평균 평점으로 정렬
    result=df.iloc[sim_index].sort_values('score', ascending=False)[:10]
    
    return result

In [85]:
recommend_movie_list(data, movie_title='Spectre')

id                     genres  vote_average  vote_count  popularity  \
828       24               Action Crime           7.7        4949   79.754966   
2085      85           Adventure Action           7.7        3854   68.159596   
1006      89           Adventure Action           7.6        3152   80.972475   
788   293660    Action Adventure Comedy           7.4       10995  514.569956   
411    22538    Action Adventure Comedy           7.2        2126   38.885195   
19    122917   Action Adventure Fantasy           7.1        4760  120.965743   
1720   23483               Action Crime           7.1        4645   45.054936   
134   177677  Action Adventure Thriller           7.1        3224  114.522237   
1697      87           Adventure Action           7.1        2781   66.976776   
531   203801    Comedy Action Adventure           7.1        2265   48.744209   

                                          title  \
828                           Kill Bill: Vol. 1   
2085                    Raiders of the Lost Ark   
1006         Indiana Jones and the Last Crusade   
788                                    Deadpool   
411                 Scott Pilgrim vs. the World   
19    The Hobbit: The Battle of the Five Armies   
1720                                   Kick-Ass   
134          Mission: Impossible - Rogue Nation   
1697       Indiana Jones and the Temple of Doom   
531                     The Man from U.N.C.L.E.   

                                               keywords  \
828   japan coma martial arts kung fu underworld yak...   
2085  saving the world riddle nepal himalaya cairo m...   
1006  saving the world venice holy grail library rid...   
788   anti hero mercenary marvel comic superhero bas...   
411   whipping hipster underage girlfriend animated ...   
19    corruption elves dwarves orcs middle-earth (to...   
1720  crime fighter secret identity comic book super...   
134   london england spy austria villain sequel miss...   
1697  riddle treasure heart skeleton treasure hunt t...   
531   spy cold war remake based on tv series buddy c...   

                                               overview     score  
828   An assassin is shot at the altar by her ruthle...  7.500378  
2085  When Dr. Indiana Jones – the tweed-suited prof...  7.461979  
1006  When Dr. Henry Jones Sr. suddenly goes missing...  7.365335  
788   Deadpool tells the origin story of former Spec...  7.337398  
411   Scott Pilgrim is a film adaptation of the crit...  7.090094  
19    Immediately after the events of The Desolation...  7.061828  
1720  Dave Lizewski is an unnoticed high school stud...  7.061151  
134   Ethan and team take on their most impossible m...  7.050246  
1697  After arriving in India, Indiana Jones is aske...  7.045475  
531   At the height of the Cold War, a mysterious cr...  7.038619